create table if not exists public.lotto_draws (
  id bigint generated by default as identity primary key,
  numbers jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.lotto_draws enable row level security;
